version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./BE/oem-ev-warranty-management-system/.env
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: be-container
    ports:
      - "8080:8080"
    env_file:
      - ./BE/oem-ev-warranty-management-system/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: fe-container
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: /api
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:

