version: "3.9"

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: be-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    container_name: fe-container
    ports:
      - "3000:8081"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

