package com.swp391.warrantymanagement.mapper;

import com.swp391.warrantymanagement.dto.request.PartRequestDTO;
import com.swp391.warrantymanagement.dto.response.PartResponseDTO;
import com.swp391.warrantymanagement.entity.Part;
import com.swp391.warrantymanagement.entity.PartCategory;

import java.util.List;
import java.util.stream.Collectors;

/**
 * PartMapper - Converts between Part Entity and DTOs
 * Handles standalone part information (NO vehicle associations)
 */
public final class PartMapper {
    private PartMapper() {}

    // Request DTO -> Entity (for create operations)
    // partId is auto-generated, no need to set it
    // NOTE: partCategory must be set separately in service layer after fetching from DB
    public static Part toEntity(PartRequestDTO requestDTO) {
        if (requestDTO == null) return null;

        Part entity = new Part();
        // partId is auto-generated by database
        entity.setPartName(requestDTO.getPartName());
        entity.setPartNumber(requestDTO.getPartNumber());
        entity.setManufacturer(requestDTO.getManufacturer());
        entity.setPrice(requestDTO.getPrice());

        // Category is set in service layer (need to fetch from DB first)
        // entity.setPartCategory(category) - handled in PartServiceImpl

        // Warranty configuration
        entity.setHasExtendedWarranty(requestDTO.getHasExtendedWarranty() != null ? requestDTO.getHasExtendedWarranty() : false);
        entity.setDefaultWarrantyMonths(requestDTO.getDefaultWarrantyMonths());
        entity.setDefaultWarrantyMileage(requestDTO.getDefaultWarrantyMileage());
        entity.setGracePeriodDays(requestDTO.getGracePeriodDays());
        entity.setPaidWarrantyFeePercentageMin(requestDTO.getPaidWarrantyFeePercentageMin());
        entity.setPaidWarrantyFeePercentageMax(requestDTO.getPaidWarrantyFeePercentageMax());

        return entity;
    }

    // Update existing entity from request DTO
    // NOTE: partCategory must be set separately in service layer after fetching from DB
    public static void updateEntity(Part entity, PartRequestDTO requestDTO) {
        if (entity == null || requestDTO == null) return;

        // Don't update partId (primary key)
        entity.setPartName(requestDTO.getPartName());
        entity.setPartNumber(requestDTO.getPartNumber());
        entity.setManufacturer(requestDTO.getManufacturer());
        entity.setPrice(requestDTO.getPrice());

        // Category is set in service layer (need to fetch from DB first)
        // entity.setPartCategory(category) - handled in PartServiceImpl

        // Warranty configuration
        entity.setHasExtendedWarranty(requestDTO.getHasExtendedWarranty() != null ? requestDTO.getHasExtendedWarranty() : false);
        entity.setDefaultWarrantyMonths(requestDTO.getDefaultWarrantyMonths());
        entity.setDefaultWarrantyMileage(requestDTO.getDefaultWarrantyMileage());
        entity.setGracePeriodDays(requestDTO.getGracePeriodDays());
        entity.setPaidWarrantyFeePercentageMin(requestDTO.getPaidWarrantyFeePercentageMin());
        entity.setPaidWarrantyFeePercentageMax(requestDTO.getPaidWarrantyFeePercentageMax());
    }

    // Entity -> Response DTO (for API response)
    public static PartResponseDTO toResponseDTO(Part entity) {
        if (entity == null) return null;

        PartResponseDTO responseDTO = new PartResponseDTO();
        responseDTO.setPartId(entity.getPartId());
        responseDTO.setPartName(entity.getPartName());
        responseDTO.setPartNumber(entity.getPartNumber());
        responseDTO.setManufacturer(entity.getManufacturer());
        responseDTO.setPrice(entity.getPrice());

        // Category information (if exists)
        PartCategory category = entity.getPartCategory();
        if (category != null) {
            responseDTO.setCategoryId(category.getCategoryId());
            responseDTO.setCategoryName(category.getCategoryName());
            responseDTO.setMaxQuantityPerVehicle(category.getMaxQuantityPerVehicle());
        }

        // Warranty configuration
        responseDTO.setHasExtendedWarranty(entity.getHasExtendedWarranty());
        responseDTO.setDefaultWarrantyMonths(entity.getDefaultWarrantyMonths());
        responseDTO.setDefaultWarrantyMileage(entity.getDefaultWarrantyMileage());
        responseDTO.setGracePeriodDays(entity.getGracePeriodDays());
        responseDTO.setPaidWarrantyFeePercentageMin(entity.getPaidWarrantyFeePercentageMin());
        responseDTO.setPaidWarrantyFeePercentageMax(entity.getPaidWarrantyFeePercentageMax());

        return responseDTO;
    }

    // List Entity -> List Response DTO
    public static List<PartResponseDTO> toResponseDTOList(List<Part> entities) {
        if (entities == null) return null;
        return entities.stream()
                .map(PartMapper::toResponseDTO)
                .collect(Collectors.toList());
    }
}
