-- =====================================================
-- TEST DATA SQL SCRIPT (Generated from Entity classes)
-- OEM EV Warranty Management System
-- =====================================================
-- Purpose: Populate database with test data matching Entity structure
-- Generated from: Entity classes in com.swp391.warrantymanagement.entity
-- Usage: Run after application creates tables (spring.jpa.hibernate.ddl-auto=update)
--
-- Passwords match DataInitializer.java:
-- - admin: admin123
-- - others: 1234567
-- =====================================================

SET FOREIGN_KEY_CHECKS = 0;

-- =====================================================
-- 1. ROLES (Master Data)
-- =====================================================
-- Entity: Role.java
-- Table: roles
-- Columns: role_id (BIGINT AUTO), role_name (VARCHAR(50) UNIQUE NOT NULL)

INSERT INTO roles (role_id, role_name) VALUES
(1, 'ADMIN'),
(2, 'EVM_STAFF'),
(3, 'SC_STAFF'),
(4, 'SC_TECHNICIAN'),
(5, 'CUSTOMER')
ON DUPLICATE KEY UPDATE
    role_name = VALUES(role_name);

-- =====================================================
-- 2. SERVICE CENTERS
-- =====================================================
-- Entity: ServiceCenter.java
-- Table: service_centers
-- Columns: service_center_id, name, address, phone, opening_hours, latitude, longitude

INSERT INTO service_centers (service_center_id, name, address, phone, opening_hours, latitude, longitude) VALUES
(1, N'Trung Tâm Bảo Hành Chính Hãng Hà Nội', N'123 Nguyễn Trãi, Thanh Xuân, Hà Nội', '0243456789', N'Thứ 2-6: 8:00-17:00, Thứ 7: 8:00-12:00', 21.0285, 105.8542),
(2, N'Trung Tâm Bảo Hành Chính Hãng TP.HCM', N'456 Lê Lại, Quận 1, TP.HCM', '0283456789', N'Thứ 2-7: 8:00-18:00, CN: Nghỉ', 10.7769, 106.7009)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    address = VALUES(address),
    phone = VALUES(phone),
    opening_hours = VALUES(opening_hours),
    latitude = VALUES(latitude),
    longitude = VALUES(longitude);

-- =====================================================
-- 3. USERS
-- =====================================================
-- Entity: User.java
-- Table: users
-- Columns: user_id, username, email, password, address, created_at, role_id, service_center_id
-- Note: created_at is auto-generated by @PrePersist, but we set it manually in SQL

-- Admin user (password: admin123)
INSERT INTO users (user_id, username, email, password, address, created_at, role_id, service_center_id) VALUES
(1, 'admin', 'admin@warranty.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', N'Hệ Thống', NOW(), 1, NULL)
ON DUPLICATE KEY UPDATE
    password = VALUES(password),
    email = VALUES(email);

-- EVM Staff (password: 1234567)
INSERT INTO users (user_id, username, email, password, address, created_at, role_id, service_center_id) VALUES
(2, 'evmstaff', 'evm.staff@manufacturer.com', '$2a$10$eImiTXuWVxfM37uY4JANjO8YRqBJFBAa3sMlm0KfHvPXPz7xWPKPi', N'Trụ Sở EVM', NOW(), 2, NULL)
ON DUPLICATE KEY UPDATE
    password = VALUES(password),
    email = VALUES(email);

-- SC Staff (password: 1234567) - Assigned to Service Center 1
INSERT INTO users (user_id, username, email, password, address, created_at, role_id, service_center_id) VALUES
(3, 'scstaff', 'sc.staff@servicecenter.com', '$2a$10$eImiTXuWVxfM37uY4JANjO8YRqBJFBAa3sMlm0KfHvPXPz7xWPKPi', N'Trung Tâm Hà Nội', NOW(), 3, 1)
ON DUPLICATE KEY UPDATE
    password = VALUES(password),
    email = VALUES(email);

-- SC Technician (password: 1234567) - Assigned to Service Center 1
INSERT INTO users (user_id, username, email, password, address, created_at, role_id, service_center_id) VALUES
(4, 'technician', 'technician@servicecenter.com', '$2a$10$eImiTXuWVxfM37uY4JANjO8YRqBJFBAa3sMlm0KfHvPXPz7xWPKPi', N'Trung Tâm Hà Nội', NOW(), 4, 1)
ON DUPLICATE KEY UPDATE
    password = VALUES(password),
    email = VALUES(email);

-- Customer user (password: 1234567)
INSERT INTO users (user_id, username, email, password, address, created_at, role_id, service_center_id) VALUES
(5, 'customer', 'customer@email.com', '$2a$10$eImiTXuWVxfM37uY4JANjO8YRqBJFBAa3sMlm0KfHvPXPz7xWPKPi', N'123 Đường ABC, Quận 1, TP.HCM', NOW(), 5, NULL)
ON DUPLICATE KEY UPDATE
    password = VALUES(password),
    email = VALUES(email);

-- =====================================================
-- 4. CUSTOMERS
-- =====================================================
-- Entity: Customer.java
-- Table: customers
-- Columns: customer_id (UUID VARCHAR(36)), name, phone, user_id
-- Note: customer_id must be manually generated UUID

INSERT INTO customers (customer_id, name, phone, user_id) VALUES
('550e8400-e29b-41d4-a716-446655440001', N'Nguyễn Văn An', '0901234571', 5)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    phone = VALUES(phone);

-- =====================================================
-- 5. VEHICLES
-- =====================================================
-- Entity: Vehicle.java
-- Table: vehicles
-- Columns: vehicle_id, vehicle_name, vehicle_model, vehicle_year, vehicle_vin,
--          purchase_date, warranty_start_date, warranty_end_date, mileage, customer_id

INSERT INTO vehicles (vehicle_id, vehicle_name, vehicle_model, vehicle_year, vehicle_vin, purchase_date, warranty_start_date, warranty_end_date, mileage, customer_id) VALUES
(1, N'Tesla Model 3 Của Tôi', 'Model 3 Standard Range Plus', 2024, 'VIN1234567890ABCDE', '2024-01-15', '2024-01-15', '2027-01-15', 5000, '550e8400-e29b-41d4-a716-446655440001'),
(2, N'VinFast VF8 Của Tôi', 'VF8 Eco', 2024, 'VIN0987654321ZYXWV', '2024-03-20', '2024-03-20', '2027-03-20', 3000, '550e8400-e29b-41d4-a716-446655440001')
ON DUPLICATE KEY UPDATE
    vehicle_name = VALUES(vehicle_name),
    mileage = VALUES(mileage);

-- =====================================================
-- 6. PARTS (Master Data)
-- =====================================================
-- Entity: Part.java
-- Table: parts
-- Columns: part_id, part_name, part_number, manufacturer, price, warranty_months, stock_quantity

INSERT INTO parts (part_id, part_name, part_number, manufacturer, price, warranty_months, stock_quantity) VALUES
(1, N'Pin Lithium 75kWh', 'BAT-75KWH-001', N'LG Energy Solution', 150000000.00, 96, 50),
(2, N'Motor Điện 250kW', 'MOT-250KW-001', N'Bosch Automotive', 80000000.00, 60, 30),
(3, N'Bộ Nghịch Lưu DC-AC', 'INV-DCAC-001', N'Siemens', 35000000.00, 36, 100),
(4, N'Hệ Thống Phanh ABS', 'BRK-ABS-001', N'Continental', 25000000.00, 24, 75)
ON DUPLICATE KEY UPDATE
    part_name = VALUES(part_name),
    price = VALUES(price),
    stock_quantity = VALUES(stock_quantity);

SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
-- Uncomment to verify data after import

-- Check roles
-- SELECT * FROM roles ORDER BY role_id;

-- Check users with their roles
-- SELECT u.user_id, u.username, u.email, r.role_name, sc.name as service_center
-- FROM users u
-- JOIN roles r ON u.role_id = r.role_id
-- LEFT JOIN service_centers sc ON u.service_center_id = sc.service_center_id
-- ORDER BY u.user_id;

-- Check customers
-- SELECT c.customer_id, c.name, c.phone, u.username
-- FROM customers c
-- JOIN users u ON c.user_id = u.user_id;

-- Check vehicles with customer info
-- SELECT v.vehicle_id, v.vehicle_name, v.vehicle_model, v.vehicle_vin,
--        v.warranty_end_date, c.name as customer_name
-- FROM vehicles v
-- JOIN customers c ON v.customer_id = c.customer_id;

-- Check parts
-- SELECT part_id, part_name, part_number, manufacturer,
--        CONCAT('₫', FORMAT(price, 0)) as price_formatted,
--        warranty_months, stock_quantity
-- FROM parts
-- ORDER BY part_id;

-- =====================================================
-- TEST CREDENTIALS SUMMARY
-- =====================================================
-- Username: admin      | Password: admin123 | Role: ADMIN
-- Username: evmstaff   | Password: 1234567  | Role: EVM_STAFF
-- Username: scstaff    | Password: 1234567  | Role: SC_STAFF (Service Center 1)
-- Username: technician | Password: 1234567  | Role: SC_TECHNICIAN (Service Center 1)
-- Username: customer   | Password: 1234567  | Role: CUSTOMER
-- =====================================================
-- BCrypt hashes used:
-- - admin123: $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
-- - 1234567:  $2a$10$eImiTXuWVxfM37uY4JANjO8YRqBJFBAa3sMlm0KfHvPXPz7xWPKPi
-- =====================================================
-- Data includes:
-- - 5 Roles (ADMIN, EVM_STAFF, SC_STAFF, SC_TECHNICIAN, CUSTOMER)
-- - 2 Service Centers (Hanoi & HCMC)
-- - 5 Users (one per role, with proper service_center assignments)
-- - 1 Customer (linked to customer user)
-- - 2 Vehicles (both owned by the customer)
-- - 4 Parts (Battery, Motor, Inverter, Brake System)
-- =====================================================
